platform :ios, '9.0'
use_frameworks!

project "RxFire.xcodeproj"

abstract_target 'ProjectAbstractTargets' do
  pod 'RxFire', :path => '../'
  pod 'RxSwift', '~> 3.5.0'

  target 'RxFireExampleApplication'

  target 'UnitTests' do
    pod 'Quick', '~> 1.1.0'
    pod 'Nimble', '~> 7.0.1'
    pod 'RxTest', '~> 3.5.0'
  end
end
